default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rails
  password: rails
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_development


production:
  <<: *default
  database: demo_production
